---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: dcall external script
description: calls an external script
inputs:
  argone:
    description: simple arg to test
    required: true
  
  
runs:
  using: composite
  steps:
    - id: call_script
      name: Call The Script
      uses: docker://alpine/helm:latest
      shell: sh
      run: |
        ./script.sh
         
